// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgmjrejujgklxsvnpsnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnbWpyZWp1amdrbHhzdm5wc25jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MDI0MzMsImV4cCI6MjA2NTI3ODQzM30.vgsMZkGgfUXcHb3lV8_lpWDJhMdy02-KUDZ-t-KO1pA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);